version: 2.1

orbs:
  windows: circleci/windows@2.4.1

jobs:
  build-and-test-windows-dev:
    executor:
      name: windows/default
      shell: powershell.exe

    steps:
      - checkout
      # upgrade
      - run:
          command: pip install --upgrade --user pip setuptools wheel
          name: pip install --upgrade --user pip setuptools wheel
      # pip require package
      - run:
          command: pip install --user -r dev_requirements.txt
          name: pip dev_requirements.txt
      - run:
          command: |
            $SourceURL = "https://download.mozilla.org/?product=firefox-latest&os=win&lang=en-US";
            $Installer = $env:TEMP + "\firefox.exe";
            Invoke-WebRequest $SourceURL -OutFile $Installer;
            Start-Process -FilePath $Installer -Args "/s" -Verb RunAs -Wait;
            Remove-Item $Installer;
          name: install firefox
      # desired_capabilities test
      - run:
          command: python ./test/unit_test/desired_capabilities_test/desired_capabilities_test.py
          name: desired_capabilities_test
      # find_and_click test
      - run:
          command: python ./test/unit_test/find_and_click_test/find_and_click_test.py
          name: find_and_click_test
      # multi_driver test
      - run:
          command: python ./test/unit_test/multi_driver_test/multi_driver_test.py
          name: multi_driver test
      # start_webdriver_and_asset_title test
      - run:
          command: python ./test/unit_test/start_webdriver_and_asset_title_test/title_test.py
          name: start_webdriver_and_asset_title test
      # get_webdriver test
      - run:
          command: python ./test/unit_test/start_webdriver_test/get_webdriver.py
          name: get_webdriver
      # start_webdriver_with_options test
      - run:
          command: python ./test/unit_test/start_webdriver_with_options/webdriver_with_options.py
          name: start_webdriver_with_options
      # test_object test
      - run:
          command: python ./test/unit_test/test_object_test/test_object_test.py
          name: test_object_test
      - run:
          command: python ./test/unit_test/test_record_class_test/test_record_class_test.py
          name: test_record_class_test
      # check_value test
      - run:
          command: python ./test/unit_test/check_value_test/check_value_test.py
          name: check_value_test
      # switch test
      - run:
          command: python ./test/unit_test/switch_test/switch_test.py
          name: switch_test
      # close_choose_webdriver test
      - run:
          command: python ./test/unit_test/close_choose_webdriver_test/close_choose_webdriver_test.py
          name: close_choose_webdriver_test
      # redirect test
      - run:
          command: python ./test/unit_test/redirect_test/redirect_test.py
          name: redirect_test
      # cookie test
      - run:
          command: python ./test/unit_test/cookie_test/cookie_test.py
          name: cookie_test
      # set_timeout test
      - run:
          command: python ./test/unit_test/set_timeout_test/set_timeout_test.py
          name: set_timeout_test
      # action_chains test
      - run:
          command: python ./test/unit_test/action_chains_test/action_chains_test.py
          name: action_chains_test
      # window test
      - run:
          command: python ./test/unit_test/window_test/window_test.py
          name: window_test
      # screenshot test
      - run:
          command: python ./test/unit_test/screenshot_test/screenshot_test.py
          name: screenshot_test
      # executor test
      - run:
          command: python ./test/unit_test/executor_test/executor_test.py
          name: executor_test
      # argparse test
      - run:
          command: python ./test/unit_test/argparse/argparse_test.py
          name: screenshot_test
      # html report test
      - run:
          command: python ./test/unit_test/html_report_test/html_report_test.py
          name: html_report_test

  build-and-test-windows-stable:
    executor:
      name: windows/default
      shell: powershell.exe

    steps:
      - checkout
      # upgrade
      - run:
          command: pip install --upgrade --user pip setuptools wheel
          name: pip install --upgrade --user pip setuptools wheel
      # pip require package
      - run:
          command: pip install --user -r requirements.txt
          name: pip requirements.txt
      - run:
          command: |
            $SourceURL = "https://download.mozilla.org/?product=firefox-latest&os=win&lang=en-US";
            $Installer = $env:TEMP + "\firefox.exe";
            Invoke-WebRequest $SourceURL -OutFile $Installer;
            Start-Process -FilePath $Installer -Args "/s" -Verb RunAs -Wait;
            Remove-Item $Installer;
          name: install firefox
      # desired_capabilities test
      - run:
          command: python ./test/unit_test/desired_capabilities_test/desired_capabilities_test.py
          name: desired_capabilities_test
      # find_and_click test
      - run:
          command: python ./test/unit_test/find_and_click_test/find_and_click_test.py
          name: find_and_click_test
      # multi_driver test
      - run:
          command: python ./test/unit_test/multi_driver_test/multi_driver_test.py
          name: multi_driver test
      # start_webdriver_and_asset_title test
      - run:
          command: python ./test/unit_test/start_webdriver_and_asset_title_test/title_test.py
          name: start_webdriver_and_asset_title test
      # get_webdriver test
      - run:
          command: python ./test/unit_test/start_webdriver_test/get_webdriver.py
          name: get_webdriver
      # start_webdriver_with_options test
      - run:
          command: python ./test/unit_test/start_webdriver_with_options/webdriver_with_options.py
          name: start_webdriver_with_options
      # test_object test
      - run:
          command: python ./test/unit_test/test_object_test/test_object_test.py
          name: test_object_test
      - run:
          command: python ./test/unit_test/test_record_class_test/test_record_class_test.py
          name: test_record_class_test
      # check_value test
      - run:
          command: python ./test/unit_test/check_value_test/check_value_test.py
          name: check_value_test
      # switch test
      - run:
          command: python ./test/unit_test/switch_test/switch_test.py
          name: switch_test
      # close_choose_webdriver test
      - run:
          command: python ./test/unit_test/close_choose_webdriver_test/close_choose_webdriver_test.py
          name: close_choose_webdriver_test
      # redirect test
      - run:
          command: python ./test/unit_test/redirect_test/redirect_test.py
          name: redirect_test
      # cookie test
      - run:
          command: python ./test/unit_test/cookie_test/cookie_test.py
          name: cookie_test
      # set_timeout test
      - run:
          command: python ./test/unit_test/set_timeout_test/set_timeout_test.py
          name: set_timeout_test
      # action_chains test
      - run:
          command: python ./test/unit_test/action_chains_test/action_chains_test.py
          name: action_chains_test
      # window test
      - run:
          command: python ./test/unit_test/window_test/window_test.py
          name: window_test
      # screenshot test
      - run:
          command: python ./test/unit_test/screenshot_test/screenshot_test.py
          name: screenshot_test
      # executor test
      - run:
          command: python ./test/unit_test/executor_test/executor_test.py
          name: executor_test
      # argparse test
      - run:
          command: python ./test/unit_test/argparse/argparse_test.py
          name: screenshot_test
      # html report test
      - run:
          command: python ./test/unit_test/html_report_test/html_report_test.py
          name: html_report_test
workflows:
  main:
    jobs:
      - build-and-test-windows-dev
      - build-and-test-windows-stable:
          requires:
            - build-and-test-windows-dev
