name: WebRunner GitHub Actions Dev

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build_dev_version:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r dev_requirements.txt
    - name: install firefox
      run: |
            $SourceURL = "https://download.mozilla.org/?product=firefox-latest&os=win&lang=en-US";
            $Installer = $env:TEMP + "\firefox.exe";
            Invoke-WebRequest $SourceURL -OutFile $Installer;
            Start-Process -FilePath $Installer -Args "/s" -Verb RunAs -Wait;
            Remove-Item $Installer;
      # desired_capabilities_test
    - name: desired_capabilities_test
      run: python ./test/unit_test/desired_capabilities_test/desired_capabilities_test.py
      # find_and_click_test
    - name: find_and_click_test
      run: python ./test/unit_test/find_and_click_test/find_and_click_test.py
      # multi_driver_test
    - name: multi_driver_test
      run: python ./test/unit_test/multi_driver_test/multi_driver_test.py
      # start_webdriver_and_asset_title test
    - name: start_webdriver_and_asset_title_test
      run: python ./test/unit_test/start_webdriver_and_asset_title_test/title_test.py
      # get_webdriver_test
    - name: get_webdriver
      run: python ./test/unit_test/start_webdriver_test/get_webdriver.py
      # start_webdriver_with_options test
    - name: start_webdriver_with_options
      run: python ./test/unit_test/start_webdriver_with_options/webdriver_with_options.py
      # test_object_test
    - name: test_object_test
      run: python ./test/unit_test/test_object_test/test_object_test.py
    - name: test_record_class_test
      run: python ./test/unit_test/test_record_class_test/test_record_class_test.py
      # check_value_test
    - name: check_value_test
      run: python ./test/unit_test/check_value_test/check_value_test.py
      # switch_test
    - name: switch_test
      run: python ./test/unit_test/switch_test/switch_test.py
      # close_choose_webdriver_test
    - name: close_choose_webdriver_test
      run: python ./test/unit_test/close_choose_webdriver_test/close_choose_webdriver_test.py
      # redirect_test
    - name: redirect_test
      run: python ./test/unit_test/redirect_test/redirect_test.py
      # cookie_test
    - name: cookie_test
      run: python ./test/unit_test/cookie_test/cookie_test.py
      # set_timeout_test
    - name: set_timeout_test
      run: python ./test/unit_test/set_timeout_test/set_timeout_test.py
      # action_chains_test
    - name: action_chains_test
      run: python ./test/unit_test/action_chains_test/action_chains_test.py
      # window_test
    - name: window_test
      run: python ./test/unit_test/window_test/window_test.py
      # screenshot_test
    - name: screenshot_test
      run: python ./test/unit_test/screenshot_test/screenshot_test.py
      # executor_test
    - name: executor_test
      run: python ./test/unit_test/executor_test/executor_test.py
      # argparse_test
    - name: argparse_test
      run: python ./test/unit_test/argparse/argparse_test.py
      # html_report_test
    - name: html_report_test
      run: python ./test/unit_test/html_report_test/html_report_test.py